name: recparenting
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.1
  webview_flutter: ^4.2.4
  flutter_native_splash: ^2.3.2
  icons_launcher: ^2.1.3
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.1
  dio: ^5.3.2
  bloc: ^8.1.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: ProximaSoft
      fonts:
        - asset: assets/fonts/Proxima-Soft_Light.ttf
        - asset: assets/fonts/ProximaSoftExtraBold.ttf
          weight: 700
        