// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxeJw-9-TfwjEMGhTrwePQKoNo1Yun5uE',
    appId: '1:668582933449:android:1b1b8407c43c696ee82e18',
    messagingSenderId: '668582933449',
    projectId: 'pushb-9f459',
    databaseURL: 'https://pushb-9f459.firebaseio.com',
    storageBucket: 'pushb-9f459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARnZ7u6PWtSPyFcenJCpOQDMyk5ihuFFs',
    appId: '1:668582933449:ios:634e325e64626257e82e18',
    messagingSenderId: '668582933449',
    projectId: 'pushb-9f459',
    databaseURL: 'https://pushb-9f459.firebaseio.com',
    storageBucket: 'pushb-9f459.appspot.com',
    androidClientId: '668582933449-cjh1emsu7kosuujbuo7e7a7fv5ondflq.apps.googleusercontent.com',
    iosBundleId: 'appmobile.recparenting',
  );
}
